tensorflow/probability

tensorflow_probability/python/bijectors/matrix_inverse_tril_test.py
The inverse of 0 is undefined, so when computing the inverse of a lower
triangular numpy array, we need to ensure the zeros in the upper
parts of the triangle remain as zero. After doing the inverse
of an array, iterator over the array and set the values above the
main diagonal to zero.
See: numpy/numpy#11445
Original PR from Tensorflow: tensorflow/tensorflow#20477
=> Fix matrix_inverse_tril_test handling the inverse of 0

tensorflow_probability/examples/vae.py
In py3 `"1" != b"1"`, thus all the images are fully black.
=> Fixed examples\vae.py parsing on py3

tensorflow_probability/python/bijectors/sinh_arcsinh_test.py
Skipped the check that fails due to overflow error as float128 data type
is same as float64 instead of longdouble on platforms like ppc64le.
Original PR from Tensorflow: tensorflow/tensorflow#19860
=> Fix sinh_arcsinh_bijector_test on ppc64le

tensorflow_probability/examples/logistic_regression.py
The color map "binary" makes negative samples blank in the scatter plot. I tried many color maps and chose "Reds" for better visualization.
=> Minor changes to scatter plot for better visualization.

tensorflow_probability/g3doc/api_docs/python/tfp/distributions/GaussianProcessRegressionModel.md, tensorflow_probability/python/distributions/gaussian_process_regression_model.py
Example code threw an error because of a missing parenthesis
=> Fixed example code in GP regression

tensorflow_probability/python/edward2/README.md
Just fix typo from `kernels_results` to `kernel_results` as `kernel_results` is declared few lines of code before (not `kernels_results`).
=> Fix typo: edward2 README

tensorflow_probability/python/mcmc/sample.py
Fixes a typo in the `sample_chain` docstring.
=> Fix typo in sample_chain docstring.

tensorflow_probability/python/mcmc/metropolis_hastings.py, tensorflow_probability/python/mcmc/sample.py, tensorflow_probability/python/util/variables.py
Fixes https://github.com/tensorflow/probability/issues/237
- We shouldn't have been setting the global warning filters
- Do not call `warnings.simplefilter()` as part of the API
- It is now up to the user of the API to set the warnings filter appropriately for them
=> Don't globally set warning filters

tensorflow_probability/python/distributions/gaussian_process.py
A minor change I found following the API examples. `tfp.GaussianProcess` does not exist, as is also visible in the example just above it. The correct module is `tfd`.
=> Fix typo in tfd.GaussianProcess API docs

tensorflow_probability/python/distributions/gaussian_process.py
As discussed in #261. I kept the `NLL` string in the print statements to avoid making it overly verbose, but let me know if you want it changed too and I can update the PR :)
=> Fix doc typo in `tfd.GaussianProcess`

tensorflow_probability/python/positive_semidefinite_kernels/internal/util.py, tensorflow_probability/python/positive_semidefinite_kernels/internal/util_test.py
I get an error when I use a tensor with dynamic shape as the index_points in `tfd.GaussianProcess`. This change fixed the problem.
=> Support dynamic shape in `sqrt_with_finite_grads`.

tensorflow_probability/python/mcmc/util.py
The function used is not present in TF 1.13.
=> Remove logic to prevent mcmc loop unrolling in XLA

tensorflow_probability/python/layers/distribution_layer_test.py
The requisite dynamic shape support in Keras is not present in TF 1.13
=> Disable dynamic shape test in distribution_layers_test

tensorflow_probability/python/distributions/autoregressive.py
The example codes in autoregressive seems outdated. I made some changes to make it work.
=> Fix examples in `tfd.autoregressive` docstring

tensorflow_probability/python/bijectors/kumaraswamy.py
Hi, I just noticed this during creating R bindings for bijectors... I'm imagining it would be clearer not to have defaults for these arguments?
=> indicate that these arguments are not optional

tensorflow_probability/examples/generative_adversarial_network.py
Hi TFP team, I added an example for generating MNIST-like images with GAN. Please let me know if there are changes needed.
Adapted from http://edwardlib.org/tutorials/gan
Fix #63
=> Example for MNIST with Generative Adversarial Network.

tensorflow_probability/g3doc/api_docs/python/tfp/distributions/GaussianProcessRegressionModel.md, tensorflow_probability/python/distributions/gaussian_process_regression_model.py
The example in [Marginalization of model hyperparameters](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/GaussianProcessRegressionModel#marginalization_of_model_hyperparameters) section crashes, because the `index_points` variable doesn't have the correct shape. This change fixes that.
In this snippet, `index_points` is never set. However, it is set in a previous snippet, but the shape is not correct, and this example crashes when it goes to plot the results.
[Here's the working code in action](https://repl.it/@PjTrainor/tfp-gpr-text)
Per the CONTRIBUTING.md, this seemed like it was small enough for a PR without an Issue 🙂
=> fix broken example GaussianProcessRegressionModel

tensorflow_probability/python/sts/fitting.py
small fix for a typo in the docs, as mentioned in https://github.com/tensorflow/probability/issues/348
=> fix typo in docs for default num_variational_steps

tensorflow_probability/python/distributions/kumaraswamy.py
Hi,
it seems that the entropy of the Kumaraswamy distribution is implemented wrong. The implementation follows the entropy stated in Wikipedia (https://en.wikipedia.org/w/index.php?title=Kumaraswamy_distribution&oldid=885024421) which is also wrong. I put the link to the version at the time of writing because I am about to change Wikipedia as well. The correct entropy as stated in [1](pag. 100) is
which is not what is implemented.
There is the need of chaining:
`return (1 - 1. / a) + (1 - 1. / b) * _harmonic_number(b) + tf.math.log(a) + tf.math.log(b)`
to
`return (1 - 1. / b) + (1 - 1. / a) * _harmonic_number(b) - tf.math.log(a) - tf.math.log(b)`
As an empirical proof that it is wrong, a Monte Carlo estimate of the entropy doesn't match the output of the entropy function. Where the …
=> Fixing wrong entropy of the Kumaraswamy distribution

tensorflow_probability/python/distributions/gaussian_process.py
This PR fixes a typo and some bugs in the `GaussianProcess` class.
The typo was simple, but I'm not sure about the bugs 🐛. This is what happens:
```py
tf.get_variable('amplitude', np.float32)
tf.get_variable('amplitude', shape=(), dtype=np.float32)
tf.get_variable('amplitude', shape=(), dtype=np.float64)
```
See a [running repl.it](https://repl.it/@PjTrainor/tfp-gpr-example) for more details. **Note**: sometimes this crashes with `Input matrix is not invertible.`
The repl is running on tensorflow-1.13.1, so maybe there's an issue with that 🤷‍♂️
=> fixed typos and bugs in gaussian_process doc

tensorflow_probability/g3doc/api_docs/python/tfp/distributions/HiddenMarkovModel.md, tensorflow_probability/python/distributions/hidden_markov_model.py
https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/HiddenMarkovModel
I believe `tfp.zeros()` should be `tf.zeros()`.
I didn't open issue for this since this is just a small document/comment fix.
=> Fix a typo in API doc tfp.distributions.HiddenMarkovModel

tensorflow_probability/python/mcmc/diagnostic.py
I think this would be much easier to find if it was named `tfp.mcmc.r_hat`. At first, looking through the API, I thought `tfp` didn't implement R-hat. Maybe create an alias for `tfp.mcmc.r_hat`?
Also, not sure if the colon in `state.shape[1 + independent_chain_ndims:]` is intentional.
=> docs: fix typos in potential_scale_reduction docstring

.travis.yml
This fixes it by switching the python interpreter version on Travis to
be the one provided by the Ubuntu repositories. Concretely, that version
of the interpreter has the 'random' module built in, so it doesn't get
overridden by a local copy of it in the numpy backend directory.
=> Fix numpy_test on Travis.

tensorflow_probability/python/distributions/triangular.py, tensorflow_probability/python/distributions/triangular_test.py
Previously produced a nonzero density at the low point, since the left_of_peak condition did not include the low point.
=> Fix Triangular bounds (fixes #391)

tensorflow_probability/python/edward2/Upgrading_From_Edward_To_Edward2.md
The correct format for the distribution x is 
x = Poisson(tf.matmul(z0, w0))
rather than
x = Poisson(tf.matmul(z1, w0))
=> Fix typo in matrix multiplication

tensorflow_probability/python/internal/distribution_util.py
Identity is not the same thing as equality in Python.  We want the latter in this instance.
Use ==/!= to compare str, bytes, and int literals.
$ __python__
```python
>>> id = "i"
>>> id += 'd'
>>> id
'id'
>>> id == 'id'
True
>>> id is 'id'
False
>>> 0 == 0.0
True
>>> 0 is 0.0
False
```
=> Identity is not the same thing as equality in Python

tensorflow_probability/python/layers/dense_variational_v2.py
I'm not completely sure why the existing code checks for  `use_exact_kl is None`, but wouldn't the user expect that if she passes `True` here she gets the exact KL?
Perhaps I'm missing sth but I don't see what...
=> check for use_exact_kl == True instead of None

tensorflow_probability/python/positive_semidefinite_kernels/exponentiated_quadratic.py, tensorflow_probability/python/positive_semidefinite_kernels/rational_quadratic.py
Addresses #484 
The docs for [ExponentiatedQuadratic](https://www.tensorflow.org/probability/api_docs/python/tfp/positive_semidefinite_kernels/ExponentiatedQuadratic) and [RationalQuadratic](https://www.tensorflow.org/probability/api_docs/python/tfp/positive_semidefinite_kernels/RationalQuadratic) don't specify what happens when kernels are called with their default parameters.
The I've added the following sentence in the appropriate places:
> "A value of `None` is treated like 1."  
This is consistent with the documentation for the other kernels.
=> 484 update psd kernel docs

tensorflow_probability/python/sts/autoregressive.py
A space before triple tick marks ` ``` ` was causing some bad rendering.
See the [docs for `AutoregressiveStateSpaceModel`](https://www.tensorflow.org/probability/api_docs/python/tfp/sts/AutoregressiveStateSpaceModel) and [`Autoregressive`](https://www.tensorflow.org/probability/api_docs/python/tfp/sts/Autoregressive). Alternatively, see the images below, and note the triple tick mark.
`AutoregressiveStateSpaceModel`
`Autoregressive`
=> fix formatting typos in Autoregression docs

tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py
If we take the code sample provided in the [issue](https://github.com/tensorflow/probability/issues/407), we can see the memory usage keeps increasing.
```
layer = tfp.layers.DistributionLambda(tfp.distributions.Categorical)
for _ in range(int(1e6)):
dist = layer([-.23, 1.23, 1.42])
```
For each call of the layer, a new instance of _TensorCoercible is created (distribution_layer.py line 165).
```
distribution = dtc._TensorCoercible(  # pylint: disable=protected-access
distribution=d,
convert_to_tensor_fn=maybe_composite_convert_to_tensor_fn)
```
In the \_\_new__ call of _TensorCoercible, a new type based of the distribution is created, and the new instance is assigned to this type (distribution_tensor_coercible.py 54):
```
self.__class__ = …
```
=> Fixing issue 407: DistributionLambda memory issue

README.md
Since Edward has been moved to tfp/python/experimental, links should be changed accordingly in repo's README. Old Edward2 readme link currently gives 404.
=> Update broken links in README in terms of Edward2

tensorflow_probability/python/distributions/pixel_cnn.py, tensorflow_probability/python/distributions/pixel_cnn_test.py
Training multichannel images (using log_probability) used real pixel values instead of supposed transformed values. This caused green/blue channels to be wrongly used with coeffs, which resulted weird red images.
There seemed to be no 3 channel image example in the docs, but below is one way to test:
```
import tensorflow as tf
import tensorflow_datasets as tfds
tfd = tfp.distributions
tfk = tf.keras
tfkl = tf.keras.layers
data = tfds.load('fashion_mnist')
train_data, test_data = data['train'], data['test']
def image_preprocess(x):
x = tf.cast(x['image'], tf.float32)
x_b = tf.roll(x, shift=1, axis=1)
x = tf.concat((x, x, x_b), -1)
return (x,)  # (input, output) of the model
batch_size = 16
train_it = …
```
=> Pixel cnn fixes 01

README.md
Apologies if you would prefer this request against a different branch. 
The new blog URL is https://blog.tensorflow.org/ and the README originally linked to https://medium.com/tensorflow.
=> New blog URL

tensorflow_probability/python/optimizer/bfgs.py, tensorflow_probability/python/optimizer/bfgs_test.py
As per #764 this adds `validate_args=True` (so by default the previous behaviour is maintained) to `bfgs_minimize` to allow the option of experimenting with `@tf.function(experimental_compile=True)`.
@csuter tagging you incase this is at all useful for you.
Thanks!
=> Validate optimizer args

tensorflow_probability/python/math/interpolation.py
1. SyntaxError: positional argument follows keyword argument
2. Wrong x_ref_max value (1, instead of 10)
3. Missing 1 required positional argument: 'axis'
=> Corrected example for batch_interp_regular_nd_grid function

tensorflow_probability/python/mcmc/dual_averaging_step_size_adaptation.py, tensorflow_probability/python/mcmc/sample.py
Fixed code examples in - 
- [mcmc/sample.py](https://github.com/tensorflow/probability/blob/v0.9.0/tensorflow_probability/python/mcmc/sample.py#L296-L299)
- [mcmc/dual_averaging_step_size_adaptation.py](https://github.com/tensorflow/probability/blob/v0.9.0/tensorflow_probability/python/mcmc/dual_averaging_step_size_adaptation.py#L169)
=> Fix code examples in sample and dual_averaging_step

tensorflow_probability/python/layers/distribution_layer.py
Addresses #769. 
For `VariationalGaussianProcess` class replace `name` argument with `
**kwargs` to allow passing  additional keyword arguments passed to `tf.keras.Layer` (including `name`).
=> Pass kwargs to VariationalGaussianProcess initializer

tensorflow_probability/python/distributions/linear_gaussian_ssm.py, tensorflow_probability/python/distributions/linear_gaussian_ssm_test.py
Brought up by https://stackoverflow.com/questions/60237047/how-to-decompose-and-visualise-slope-component-in-tensorflow-probability/60253426#60253426.
=> Fix bug in which `concat` wrongly interprets empty static shape as having float dtype

tensorflow_probability/examples/jupyter_notebooks/Bayesian_Gaussian_Mixture_Model.ipynb
* Issue Reference: #785
Fixed error (NameError: name 'step_sizes' is not defined) you get when you run def sample().
=> Updating variable declaration

tensorflow_probability/python/distributions/distribution_properties_test.py, tensorflow_probability/python/distributions/ordered_logistic.py, tensorflow_probability/python/distributions/ordered_logistic_test.py
Hi,
Unfortunately when I was coding up some MCMC stuff using `tfd.OrderedLogistic` I couldn't get it to work and realised the code I had previously submitted wasn't quite fit for purpose - sorry about that.
I've added some more tests which show this and I've changed the code to make them pass. Unfortunately it is a bit more complicated and slower now. I also copy-pasted the `_broadcast_cat_event_and_params` from categorical.py - hope that is OK. The broadcast/flatten/gather pattern is also based on the cdf code in categorical.py.
Thanks again!
=> fix prob batch shape bug in OrderedLogistic and fix out-of-bound category probs

tensorflow_probability/python/distributions/mixture.py
Eval is not necessary with eager execution.
This is part of the documentation update for v2 related to issue #607
=> Update example to TensorFlow 2

tensorflow_probability/python/distributions/__init__.py, tensorflow_probability/python/distributions/continuous_bernoulli.py, tensorflow_probability/python/distributions/continuous_bernoulli_test.py
We recently had a NeurIPS paper (https://arxiv.org/abs/1907.06845 and https://papers.nips.cc/paper/9484-the-continuous-bernoulli-fixing-a-pervasive-error-in-variational-autoencoders) where we introduce a new (0,1)-supported distribution: the continuous Bernoulli. This pull request implements this distribution in tensorflow distributions, as well as a unit test for the continuous Bernoulli, which follows the unit test provided for the Bernoulli distribution (with appropriate modifications). Currently passing all the tests locally, except for a slicing test, where I get an error that I do not fully understand:
tensorflow.python.framework.errors_impl.UnimplementedError: Broadcast between [1,20,3,1,2,1] and [1,20,3,1,2,1] is not supported yet.
=> Continuous bernoulli branch

tensorflow_probability/python/internal/special_math_test.py
Hello,
The assignment to `output` is unnecessary as it is redefined in line 193 before the value is used. This makes the first assignment useless.
https://github.com/tensorflow/probability/blob/ab414b238654db5fe7749a6cb5ad2e0855e908e4/tensorflow_probability/python/internal/special_math_test.py#L186-L197
This is a common weakness enumeration based on https://cwe.mitre.org/data/definitions/563.html
=> Removed unnecessary 'output' variable in _test_grad_finite()

tensorflow_probability/python/bijectors/real_nvp.py
Update the presumably outdated reference from `real_nvp_default_nvp` to `real_nvp_default_template`.
=> Update RealNVP bijector docstrings

conftest.py, tensorflow_probability/python/internal/test_util.py
Not sure how flags were passed under pytest before, I got `unrecognized argument` error even on master. So added `--absl-flag` option to `pytest` which can be used as
```
pytest tensorflow_probability/python/distributions/mixture_same_family_test.py --absl-flag='--vary_seed'
```
=> Handle app flags in pytest session hook to fix CI

README.md, tensorflow_probability/g3doc/install.md
Resolves #910 
To try and make first time contributions as easy as possible, advocate in the `README` for having `tf-nightly` installed in the environment before attempting to build TensorFlow Probability from source. Additionally replicate this information to `tensorflow_probability/g3doc/install.md` as this also covers the same material. Finally, use `python -m pip` to match the syntax used in the rest of the `README` and to adhere to best practices for `pip`, and flip the order of `--user` and `--upgrade` to match the order used in other instances in the `README`.
=> docs: Advocate for tf-nightly install for source builds

tensorflow_probability/python/stats/quantiles.py, tensorflow_probability/python/stats/quantiles_test.py
Resolves #864
This changes the behavior of `percentile` and `quantiles`, as previously the sort order had been descending. This is being changed as it differs in behavior from [NumPy's `percentile` function](https://numpy.org/doc/1.18/reference/generated/numpy.percentile.html) and the docstring describes behavior that is consistent with NumPy's implementation.
The main change occurs replacing `_sort_tensor` with a single call to [`tf.sort`](https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/sort), which is then used in `percentile`. In `_sort_tensor` [`tf.math.top_k`](https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/math/top_k) (which results in descending sort) was used. When swapped for [`tf.sort`](https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/sort) …
=> fix: Use ascending sort for percentile

CONTRIBUTING.md, testing/define_testing_alias.sh, testing/install_test_dependencies.sh, testing/run_tests.sh, testing/run_tfp_test.sh
Specifically:
- add a script wrapping bazel test invocation, setting commonly used flags
- add a sourceable alias definition script, which aliases `tfp_test` to point to the tfp_test.sh script
- add a script to install dependencies, along with checks for common pitfalls and helpful error messages.
=> Add some helper scripts for running tests and use them in travis tests.

tensorflow_probability/python/bijectors/chain.py
The [tfb.Chain](https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/Chain) documentation is not rendered correctly. Maybe because of inconsistent spacing. This PR addresses the same. 
I also want to know if there is some way to build docs locally?
=> Fixed inconsistent spaces in tfb.Chain docstring

tensorflow_probability/python/vi/optimization.py
Previously, the following error was embedded in the variational distribution function `variational_model_fn` when attempting to perform Inhomogeneous Poisson process.
```
<ipython-input-15-e3db9282b77d> in variational_model_fn()
6     tfd.Normal(loc=logit_locs, scale=tf.nn.softplus(logit_softplus_scales)),
7     reinterpreted_batch_ndims=1))
----> 8     y = yield tfd.VectorDeterministic(y)
9 q = tfd.JointDistributionCoroutine(variational_model_fn)
UnboundLocalError: local variable 'y' referenced before assignment
``` 
This change will allow the observations to be incorporated directory into this variational distribution.
=> A change for Inhomogeneous Poisson Process to work

tensorflow_probability/python/mcmc/kernel.py, tensorflow_probability/python/mcmc/transformed_kernel.py, tensorflow_probability/python/mcmc/transformed_kernel_test.py
Currently, calling `TransformedTransitionKernel` on an `inner_kernel` without a `target_log_prob_fn` will result in an error. For example, calling `TransformedTransitionKernel` on a `SimpleStepSizeAdaptation` object as the inner kernel.
Akin to how `SimpleStepSizeAdaptation` edits `step_size`, `TransformedTransitionKernel` now iterates through `inner_kernel`s until it finds a valid one, then propagates that change. Tests are included, docstring edited to reflect the change, and a `ValueError` is thrown if no `inner_kernel` satisfies the condition.
=> TransformedTransitionKernel call with missing `target_log_prob_fn` bugfix

tensorflow_probability/python/stats/sample_stats_test.py
Currently, running a Bazel command (from probability/tensorflow_probability/python/stats) akin to `bazel test sample_stats_test --test_tag_filters=-notap --test_arg=--vary_seed` will fail since numpy and tfp seeding semantics are different (tfp will accept integers outside the range [0, 2^32-1] while numpy won't). Instead of relying on creating a random state via `np.random.RandomState(seed=test_util.test_seed())`, one should directly use `test_util.test_np_rng()`. This now ensures a robust check of the test won't error.
=> Making tests more robust with numpy specific random states in tfp.stats

tensorflow_probability/python/mcmc/sample_test.py
After implementing `step_kernel` in `tfp.experimental.mcmc`, I realized `sample_chain` has no seed reproducibility test. Adding one as a sanity check for a comprehensive test suite and to hopefully better illustrate seeding semantics with some precedent.
=> Adding a seed reproducibility test to `sample_chain`

tensorflow_probability/python/optimizer/nelder_mead.py
Hi,
I have an expensive objective function which I am trying to optimize with Nelder Mead, it supports batching and stepping through the code I noticed we could take advantage of that a little more with this change, I think.
In short, previously when `objective_at_initial_vertex is None` then the code would call `objective_function` then `_evaluate_objective_multiple`. I've changed it to make a single call to `_evaluate_objective_multiple` with a bigger batch which I think is almost always preferred.
Hope it is useful, let me know if there is anything else I can do with this.
Jeff
=> small optimization for `batch_evaluate_objective=True` in Nelder Mead optimizer

tensorflow_probability/python/distributions/gaussian_process_regression_model.py
The line here is wrong:   `loc = k(t, x) @ inv(k(x, x) + v * I) @ (y - loc)` - `loc` is on both the right and left-hand side, and `y` is not defined in the context of the comment block.
I believe this term should be `f(x)` looking at formula 2.23 of Rasmussen and Williams, but worth reviewing.
=> Correction to GP formula in GP regression documentation

tensorflow_probability/python/experimental/mcmc/sample_test.py, tensorflow_probability/python/mcmc/internal/util.py, tensorflow_probability/python/mcmc/internal/util_test.py
A direct fix of the issue described in https://github.com/tensorflow/probability/issues/1033. I've also added a test for `tfp.experimental.mcmc.step_kernel` to ensure that future building blocks in the streaming MCMC framework will work as intended
=> Fixing ridiculous loop unrolling in `smart_for_loop`

tensorflow_probability/python/experimental/mcmc/covariance_reducer.py, tensorflow_probability/python/experimental/mcmc/covariance_reducer_test.py
CovarianceReducer had a typo in its parameter attribute. This PR fixes the typo, adds to the attribute test, and edits the test style to conform with self.assertEqual(expected, actual) style guidelines.
=> Fixing `parameter` typo in CovarianceReducer

tensorflow_probability/python/experimental/mcmc/BUILD, tensorflow_probability/python/experimental/mcmc/__init__.py, tensorflow_probability/python/experimental/mcmc/covariance_reducer.py, tensorflow_probability/python/experimental/mcmc/sample_discarding_kernel.py, tensorflow_probability/python/experimental/mcmc/sample_discarding_kernel_test.py, tensorflow_probability/python/experimental/mcmc/sample_fold.py, tensorflow_probability/python/experimental/mcmc/sample_fold_test.py, tensorflow_probability/python/experimental/mcmc/with_reductions.py, tensorflow_probability/python/experimental/mcmc/with_reductions_test.py
`sample_fold` is a high-level driver that automatically applies reducers to stream over MCMC samples. It draws samples from the provided `kernel`, updates reducer states with those samples, and finalizes reducer computation. This piece makes it easy to conduct streaming MCMC without worrying about manually creating the Transition Kernel onion.
Thinning/burn-in semantics follow that proposed in https://github.com/tensorflow/probability/issues/1031
=> Add `sample_fold` driver to `tfp.experimental.mcmc`

tensorflow_probability/python/experimental/mcmc/BUILD, tensorflow_probability/python/experimental/mcmc/__init__.py, tensorflow_probability/python/experimental/mcmc/sample_fold.py, tensorflow_probability/python/experimental/mcmc/sample_fold_test.py, tensorflow_probability/python/experimental/mcmc/tracing_reducer.py, tensorflow_probability/python/experimental/mcmc/tracing_reducer_test.py
`TracingReducer` allows for accumulating arbitrary functions of samples and kernel results in the streaming MCMC framework. We can now also rewrite `sample_chain` in terms of `TracingReducer` and `sample_fold`, which is also included.
=> Adding `TracingReducer` and a recreated `sample_chain` to tfp.experimental

tensorflow_probability/python/experimental/mcmc/BUILD, tensorflow_probability/python/experimental/mcmc/__init__.py, tensorflow_probability/python/experimental/mcmc/expectations_reducer.py, tensorflow_probability/python/experimental/mcmc/expectations_reducer_test.py, tensorflow_probability/python/experimental/stats/__init__.py, tensorflow_probability/python/experimental/stats/sample_stats.py, tensorflow_probability/python/experimental/stats/sample_stats_test.py
Bulking the suite of reducers with one that computes arbitrary expectations over a series of callable functions (that accept the incoming sample and kernel results).
=> Adding an Expectations Reducer to tfp.experimental.mcmc

tensorflow_probability/python/bijectors/pad.py
Reading the markdown rendered docstring from Colab, I noticed inverted backticks.
=> Markdown typo

tensorflow_probability/python/experimental/mcmc/BUILD, tensorflow_probability/python/experimental/mcmc/expectations_reducer_test.py, tensorflow_probability/python/experimental/mcmc/internal/BUILD, tensorflow_probability/python/experimental/mcmc/internal/__init__.py, tensorflow_probability/python/experimental/mcmc/internal/test_fixtures.py, tensorflow_probability/python/experimental/mcmc/sample_discarding_kernel_test.py, tensorflow_probability/python/experimental/mcmc/sample_fold_test.py, tensorflow_probability/python/experimental/mcmc/sample_test.py, tensorflow_probability/python/experimental/mcmc/tracing_reducer_test.py, tensorflow_probability/python/experimental/mcmc/with_reductions_test.py
In the Streaming MCMC Framework, a lot of tests rely on a dummy object to represent a TransitionKernel and/or Reducer. Rather than duplicating code for using (more or less) identical test objects, this PR creates a new internal file that holds all of them.
=> Adding a test fixtures internal file to `tfp.experimental.mcmc`

tensorflow_probability/python/experimental/mcmc/tracing_reducer.py
Adding a single sentence to the docstring of `TracingReducer` to clarify that a `None` size implies the use of a dynamic-shaped `TensorArray`.
=> Clarify the use of `None` size in `tfp.experimental.mcmc.TracingReducer`

tensorflow_probability/python/experimental/mcmc/covariance_reducer.py, tensorflow_probability/python/experimental/mcmc/covariance_reducer_test.py
Like with `tfp.experimental.mcmc.ExpectationsReducer`, I'm adding a kwarg to CovarianceReducer to allow the user to specify an arbitrary structure of functions to evaluate on the chain state and kernel results for covariance computation. This makes it much easier to compute covariance over the kernel results.
=> Adding transform_fn capabilities to `tfp.experimental.mcmc.CovarianceReducer`

tensorflow_probability/python/mcmc/internal/util.py, tensorflow_probability/python/mcmc/internal/util_test.py, tensorflow_probability/python/mcmc/replica_exchange_mc.py, tensorflow_probability/python/mcmc/replica_exchange_mc_test.py
Fixes #1032.
~~The changes in this PR are two-fold, but closely related (let me know if this merits two separate PRs):~~
1. ~~for the `SimpleStepSizeAdaption`, the `target_log_prob` field of the inner kernel results gets propagated to the `SimpleStepSizeAdaption` kernel results `namedtuple`~~
2. ~~while I'm not sure whether the `target_log_prob` field in results `namedtuple`s of existing kernels is used anywhere else other than in `ReplicaExchangeMC`, the change in 1.) allows, in principle, to embed the `SimpleStepSizeAdaption` kernel in the `ReplicaExchangeMC` kernel. For that to work, some further changes in the `ReplicaExchangeMC` code were necessary to propagate states to and from `SimpleStepSizeAdaption`'s inner kernel results~~
~~Currently, in `ReplicaExchangeMC`, there are …
=> Make Replica Exchange / simple step size adaption work together

tensorflow_probability/python/experimental/stats/BUILD, tensorflow_probability/python/experimental/stats/__init__.py, tensorflow_probability/python/experimental/stats/sample_stats.py, tensorflow_probability/python/experimental/stats/sample_stats_test.py
This PR adds an object that facilitates the computation of arbitrary central moments to `tfp.experimental.stats`. All intermediate moments (i.e. lower moments) are required for computation, and hence, the user has the choice to define if they want to receive all moments or simply their moment of choice via the `finalize` method.
=> Add streaming arbitrary central moments to `tfp.experimental.stats`

tensorflow_probability/python/distributions/variational_gaussian_process.py
This fixes #1083 .
`index_points = self._get_index_points(index_points)` were not used in the VariationalGaussianProcess class, in both `_batch_shape` and `_batch_shape_tensor` methods. Now the index points are correctly used to understand the batch_shape (without relying on `self.index_points`).
=> Fix: `index_points` coming from `self._get_index_points(index_points)`

tensorflow_probability/python/bijectors/masked_autoregressive.py, tensorflow_probability/python/bijectors/masked_autoregressive_test.py
I was reading the docs here: https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/AutoregressiveNetwork and couldn't immediately see how to use `conditional`. So after figuring it out I decided it would be useful to submit an example.
Simply adds an example of conditional density estimation to the doc string.
=> add example of conditional density estimation to docs

tensorflow_probability/python/mcmc/replica_exchange_mc.py
This is a quick fix for ReplicaExchangeMC when I tried to run it inside `pmap`. Without this change, I get the error
```
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/tensorflow_probability/substrates/jax/mcmc/replica_exchange_mc.py:816: in bootstrap_results
for x in init_state
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/tensorflow_probability/substrates/jax/mcmc/replica_exchange_mc.py:816: in <listcomp>
for x in init_state
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py:374: in <lambda>
lambda input, shape, name=None: np.broadcast_to(input, shape))
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/jax/numpy/lax_numpy.py:1539: in broadcast_to
shape = …
```
=> Make ReplicaExchangeMC compatible with JAX omnistaging

setup.py, tensorflow_probability/python/layers/BUILD, tensorflow_probability/python/layers/distribution_layer.py, tensorflow_probability/python/layers/distribution_layer_test.py, testing/install_test_dependencies.sh
PR also Includes cherrypick of past change to support later cloudpickle versions
=> Update jax to explicit version number on r0.11 branch

tensorflow_probability/python/layers/distribution_layer.py, tensorflow_probability/python/layers/distribution_layer_test.py
Please check my pull request about #1080 .
I solved this problem and modified a test.
I always cast Python integer to numpy.int32 because the value of numpy.int32 will upcast with computing Python integer on the Linux.
=> Fix dtype error independent normal distribution

tensorflow_probability/python/distributions/exponential.py, tensorflow_probability/python/distributions/geometric.py
=> fix the case that value < 0 for exp and geo dist

tensorflow_probability/python/bijectors/gev_cdf.py, tensorflow_probability/python/distributions/BUILD, tensorflow_probability/python/distributions/__init__.py, tensorflow_probability/python/distributions/gev.py, tensorflow_probability/python/distributions/gev_test.py, tensorflow_probability/python/distributions/hypothesis_testlib.py
=> add gev distribution and test

tensorflow_probability/python/math/gram_schmidt.py
The correct reference should be:
[3] E. Schmidt, über die Auflosung linearer Gleichungen mit unendlich vielen
Unbekannten, Rend. Circ. Mat. Pulermo (1) 25:53-77 (1908).
=> Fix typo (ijber -> über) in gram_schmidt.py

tensorflow_probability/python/layers/conv_variational.py, tensorflow_probability/python/layers/conv_variational_test.py, tensorflow_probability/python/layers/dense_variational.py, tensorflow_probability/python/layers/dense_variational_test.py
I noticed that `{dense,conv}_variational.py` modules were using local rademacher functions. Rademacher is now available at `tfp.random.rademacher`, so I thought it would be nice to have the variational layers use that instead of local ones.
=> Remove local rademachers

tensorflow_probability/examples/latent_dirichlet_allocation_distributions.py, tensorflow_probability/examples/vae.py, tensorflow_probability/python/bijectors/composition.py, tensorflow_probability/python/bijectors/masked_autoregressive.py, tensorflow_probability/python/bijectors/real_nvp.py, tensorflow_probability/python/distributions/mixture_same_family.py, tensorflow_probability/python/distributions/von_mises.py, tensorflow_probability/python/distributions/zipf.py, tensorflow_probability/python/experimental/lazybones/utils/weak_container.py, tensorflow_probability/python/internal/backend/numpy/gen/tensor_shape.py, tensorflow_probability/python/internal/cache_util.py, tensorflow_probability/python/internal/prefer_static.py, tensorflow_probability/python/internal/test_combinations.py, tensorflow_probability/python/layers/dense_variational_v2.py, tensorflow_probability/python/layers/distribution_layer.py, tensorflow_probability/python/layers/distribution_layer_test.py, tensorflow_probability/python/layers/initializers.py, tensorflow_probability/python/layers/masked_autoregressive.py, tensorflow_probability/python/layers/variable_input.py
I've written custom parsers and emitters for everything from docstrings to classes and functions. However, I recently came across an issue with the TensorFlow codebase: inconsistent use of `Args:` and `Arguments:` in its docstrings. It is easy enough to extend my parsers to support both variants, however it looks like `Arguments:` is wrong anyway, as per:
- https://google.github.io/styleguide/pyguide.html#doc-function-args @ [`ddccc0f`](https://github.com/google/styleguide/blob/ddccc0f/pyguide.md)
- https://chromium.googlesource.com/chromiumos/docs/+/master/styleguide/python.md#describing-arguments-in-docstrings @ [`9fc0fc0`](https://chromium.googlesource.com/chromiumos/docs/+/9fc0fc0/styleguide/python.md)
- https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html @ …
=> [*.py] Rename "Arguments:" to "Args:"

tensorflow_probability/python/experimental/mcmc/diagonal_mass_matrix_adaptation.py
Currently, `tf.experimental.mcmc.DiagonalMassMatrixAdaptation` will not work with float64 variance and state parts.  This is because a `tf.ones` tensor is constructed without an explicit `dtype` in `_make_momentum_distribution`.  Here's a simple suggested fix.
=> Add missing dtype in `diagonal_mass_matrix_adaptation`

tensorflow_probability/python/vi/optimization.py
I suppose `result_fn` was renamed to `trace_fn` at some point; however, the docstring was updated only partially.
=> Fix a typo in the description of fit_surrogate_posterior

tensorflow_probability/python/distributions/weibull.py
Fixed wrong indentation of the opening backtick's triplet for the last code snippet (line 86). The wrong indentation caused the official [TensorFlow Weibull API web page](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Weibull) to display everything below this code block as actual code and not as HTML content.
=> Fix indentation error for fanced code block

tensorflow_probability/python/distributions/exp_gamma.py
In prepping to implement the SigmoidBeta distribution, I reviewed the ExpGamma distribution to understand the rough code structure. I saw that the formula in the comments didn't match the code or the derivation using the change of variables formula. This PR makes the minor modifications to fix that. The formula now agrees with the log_prob formula.
=> Updated ExpGamma formula to be correct

tensorflow_probability/python/distributions/mvn_diag.py
The message to 'combine scale_identity_multiplier with scale_diag' seemed to suggest that the arguments `scale_identity_multiplier` and `scale_diag` should be combined together, but what is actually meant is that `scale_diag` should be used in favour of `scale_identity_multiplier`. The comment down below in the body of `__init__` was clearer.
=> Make deprecation warning clearer

tensorflow_probability/python/math/special.py
When compiled using `tf.function`, Owen's T function currently fails for `tf.float64` typed inputs. By way of example,
```python
import tensorflow as tf
from tensorflow_probability.python.math.special import owens_t
h = tf.cast(1, tf.float64)
a = tf.cast(1, tf.float64)
@tf.function
def closure():
return owens_t(h, a)
T = closure()  # fails
```
Fortunately, this looks to be a quick fix. The fallback values used in two `tf.where` statements simply need to be wrapped by the `numpy_dtype` helper.
=> add casting to backend for Owen's T function

tensorflow_probability/python/mcmc/random_walk_metropolis.py
Alternatively the direct link to the pdf: https://projecteuclid.org/journalArticle/Download?urlid=10.1214%2F154957804100000024
I think however the DOI link will be much more future proof.
=> Fix broken link to Random Walk Metropolis paper

tensorflow_probability/python/distributions/poisson.py, tensorflow_probability/python/distributions/poisson_test.py
Hello, the current Poisson implementation does not have anything for the survival function and using 1 - cdf etc turns out to be quite numerically unstable. I've tried to fix this in the PR, here is a short example:
``` python
import tensorflow as tf
tfd = tfp.distributions
rate = 0.123
d = tfd.Poisson(rate=rate)
for x in range(15):
fx = d.log_survival_function(x)
gx = tf.math.log(tf.math.igamma(x + 1.0, rate))
print(f"x: {x}\n\tf(x): {fx}\n\tg(x): {gx}")
```
outputs:
``` python
x: 0
f(x): -2.156440496444702
g(x): -2.156440496444702
x: 1
f(x): -4.96586799621582
g(x): -4.965866565704346
x: 2
f(x): -8.170475006103516
g(x): -8.170435905456543
x: 3
f(x): -11.658798217773438
g(x): -11.658534049987793
x: 4
f(x): -15.249238014221191
g(x): -15.367694854736328 …
```
=> more stable poisson survival function

tensorflow_probability/python/distributions/normal_inverse_gaussian_test.py, tensorflow_probability/python/experimental/mcmc/BUILD, testing/run_github_tests.sh
- Reduce number of samples taken in NormalInverseGaussian test to
eliminate an OOM.
- Disable windowed_sampling_test, possibly also due to an OOM.
=> Make the GitHub tests pass.

.github/workflows/continuous-integration.yml, testing/install_test_dependencies.sh, testing/run_github_lints.sh, testing/run_github_tests.sh
This time it appeared that pip was not installed correctly by virtualenv. I just removed virtualenv as a fix. As a matter of being more tidy, I also moved around the pip installation commands to happen before we invoke pip for various purposes. Lastly, in a mostly unrelated change, I made it clearer how to run a subset of tests inside run_github_tests.sh.
=> Fix GitHub Actions... again.

tensorflow_probability/examples/jupyter_notebooks/Factorial_Mixture.ipynb
I'm pretty sure this summation is supposed to happen over the mixtures _k_, not the covariates _i_:
=> Fix typo in LaTeX definition of Gaussian mixture

tensorflow_probability/python/math/linalg.py, tensorflow_probability/python/math/linalg_test.py
This is to fix https://github.com/tensorflow/probability/issues/1421
I am not sure the way I tested it is the preferred way, but this substrates testing is a bit fuzzy to me, so feel free to edit it (I left edits open for maintainers).
=> BUG FIX: prefer static shapes in cholesky update

tensorflow_probability/python/stats/moving_stats.py
The current documentation was wrongly parsed as markdown links, making the changes within the `()` invisible in the deployed docs, and instead showing broken links.
Changes: I removed unneeded brackets which provides a (subjectively) smoother read and also fixes the above mentioned markdown problems. I also renamed the reference to John D. Cook's Blog.
=> :memo: Fix href-markdown problems

tensorflow_probability/python/bijectors/rational_quadratic_spline.py
When using SplineParams as in the example, it was not clear to me how to set the interval width and height B as defined in the Neural Splines Flow paper. I have modified the example by adding parameters that the user can specify: the interval width, the smallest knot position, the minimum width/height of the bins (assuming that they will be equal) and the minimum slope. The default values for `min_bin_width` and `min_slope` are set as they are in the official pytorch implementation https://github.com/bayesiains/nflows/blob/master/nflows/transforms/splines/rational_quadratic.py
I believe that some comments might be needed to clarify what `nunits` is and why it is given as argument to `__call__`, as it was quite confusing to me and it's specific to using the splines with RealNVP. Otherwise, …
=> modified SplineParams example for improved clarity

tensorflow_probability/python/distributions/continuous_bernoulli.py, tensorflow_probability/python/distributions/continuous_bernoulli_test.py
Fixes a typo in the Taylor approximation of the log-normalising constant https://github.com/tensorflow/probability/issues/1511, which yielded negative KL values.
Also fixes the stability of the gradients of the mean (and thus the KL). The existing implementation was not stable for large negative logits:
```python
import numpy as np
logits = np.linspace(-100, 100, 20)[..., np.newaxis].astype(np.float32)
_, grad_logits = tfp.math.value_and_gradient(lambda x: tfp.distributions.ContinuousBernoulli(logits=x).mean(), logits)
grad_logits
```
And here's the same output from the new implementation:
```python
import numpy as np
logits = np.linspace(-100, 100, 20)[..., np.newaxis].astype(np.float32)
_, grad_logits = …
```
=> Fix ContinuousBernoulli numerical stability

tensorflow_probability/python/distributions/multivariate_student_t.py
Python example within the docstring was not closed and hence the TF page was not rendered correctly
=> Fix Multivariate Student's t-distribution docstring

tensorflow_probability/python/bijectors/batch_normalization.py
The current `BatchNormalization` docstring is broken in several ways. There's a syntax error on line https://github.com/tensorflow/probability/blob/43a9d6c3f5992a24ddf7aa3fa826a038d70697c5/tensorflow_probability/python/bijectors/batch_normalization.py#L95
and the initializers both for `tfd.Normal` and `tfd.MultivariateNormalDiag` are currently broken. This should make the example runnable (save imports).
=> Fix BatchNormalization docstring

tensorflow_probability/python/experimental/sequential/iterated_filter.py, tensorflow_probability/python/optimizer/differential_evolution.py
Backtics are not formatted well which is resulting in rendering issues. This PR updates those backticks.
=> Correctly rendering iterated_filter by correcting backticks

tensorflow_probability/python/distributions/BUILD, tensorflow_probability/python/distributions/two_piece_normal.py, tensorflow_probability/python/distributions/two_piece_normal_test.py
Add implicit reparameterization gradient w.r.t. `skewness`, making the distribution `tfd.TwoPieceNormal` fully reparameterized. The applied approach to compute the implicit gradient was proposed by Figurnov, Mohamed, and Mnih (2018)[1].
In addition to implementing the implicit gradient described above, this PR makes the following changes:
* In the file `tensorflow_probability/python/distributions/BUILD`:
* Add a new dependency
* In the file `tensorflow_probability/python/distributions/two_piece_normal.py`:
* Reorganize the file, putting all functions below the class definition
* Run all Tensor args through `tf.convert_to_tensor` in the functions `standardize`, `cdf`, and `quantile`, making them consistent with `random_two_piece_normal`
* In the file …
=> Add implicit reparameterization gradient to tfd.TwoPieceNormal

tensorflow_probability/g3doc/_index.ipynb
Use compat v2 import similarly to other tfp notebooks E.g (https://github.com/tensorflow/probability/blob/main/tensorflow_probability/examples/jupyter_notebooks/Structural_Time_Series_Modeling_Case_Studies_Atmospheric_CO2_and_Electricity_Demand.ipynb)
Current error with Tensorflow 2:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-1-188fac1083eb>](https://localhost:8080/#) in <module>()
2 import tensorflow_probability as tfp
3 
----> 4 tf.enable_eager_execution()
5 
6 print(tf.__version__)
```
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'
=> TensorFlow Probability: import tensorflow.compat.v2

tensorflow_probability/python/distributions/empirical.py, tensorflow_probability/python/distributions/empirical_test.py
Fixes #1549
Implemented the quantile method for the Empirical distribution class by interfacing the `tfp.stats.percentile` method and scaling the input appropriately. I think that the tests pass locally. I've tested using the command below: 
`bazel test -c opt tensorflow_probability/python/distributions:normal_test \
--test_arg=--test_regex=EmpiricalScalarTest`
Let me know if I need to add more tests in the `EmpiricalNdTest` and the `EmpiricalVectorTest` classes. 
Thanks!
=> Empirical distributions quantiles

tensorflow_probability/python/distributions/student_t.py
The docstring contained a typo:
An exception is raised if `self.allow_nan_stats=False` when df <=1
=> Fix: typo in docstring

tensorflow_probability/python/distributions/joint_distribution_sequential.py
There is a `,` missing in the example codes in the doc of `joint_distribution_sequential.py`.
=> Correct a typo in the doc of joint_distribution_sequential.py

tensorflow_probability/python/sts/anomaly_detection/anomaly_detection_lib.py
In order to override the default value of anomaly_threshold variable, we are to pass this value as a parameter
Fixes https://github.com/tensorflow/probability/issues/1587
=> issue 1587 pass anomaly_threshold parameter

tensorflow_probability/python/math/BUILD, tensorflow_probability/python/math/special.py, tensorflow_probability/python/math/special_test.py
This PR tries to improve the partial derivatives of ` tfp_math.betainc(a, b, x)` with respect to `a` and `b`.
Some of the improvement opportunities I identified in the current implementation of these partial derivatives are:
- When dtype is `float64`:
- Moderate loss of accuracy when `a` and `b` are uniformly distributed in the interval (0, 10).
- When `a` and `b` are very small, gradients contain a very high proportion of NaN.
- When dtype is `float32`:
- Heavy loss of accuracy in all domains evaluated.
- Gradients contain NaN (sometimes infinite as well) in all domains evaluated.
- When `a` and `b` are very small, gradients contain only NaN.
Please see the following notebook:
https://gist.github.com/leandrolcampos/c5a77b0f24ee8d2a38c9ea2f8ddc3c77
The alternative implementation I propose …
=> Improve the partial derivatives of tfp_math.betainc

tensorflow_probability/python/math/__init__.py, tensorflow_probability/python/math/special.py, tensorflow_probability/python/math/special_test.py
This PR provides an implementation for `tfp.math.betaincinv`, the inverse of the regularized incomplete beta function (`tfp.math.betainc`) with respect to `x`. It addresses the issue #1581.
This implementation is based on ideas and equations available in the following references:
[1] Milton Abramowitz and Irene A. Stegun. Handbook of Mathematical Functions with Formulas, Graphs, and Mathematical Tables. US Government Printing Office, 1964 (reprinted 1972). [[Link](https://archive.org/details/AandS-mono600)]
[2] William Press, Saul Teukolsky, William Vetterling and Brian Flannery. Numerical Recipes: The Art of Scientific Computing. Cambridge University Press, 2007 (Third Edition). [[Link](http://numerical.recipes/book/book.html)]
[3] John Maddock, Paul A. Bristow, et al. The Incomplete …
=> Add `tfp.math.betaincinv`

CONTRIBUTING.md, testing/get_github_changed_py_files.sh, testing/install_test_dependencies.sh, testing/run_github_tests.sh
Also:
- Correctly detect unset environment variables
- Ignore another non-nightly-but-safe TF package.
- Skip testing numpy tests (it doesn't look like they were skipped before, but that was definitely the intention... whoops)
=> Only run affected tests in the GitHub workflow.

tensorflow_probability/python/stats/calibration.py
The range of values should be from 0 to nlabels-1. Including nlabels would give you one too many.
=> There is a typo in the description

tensorflow_probability/python/distributions/matrix_normal_linear_operator.py
Sorry it took me so long to open this PR!
As per the original issue #1497 , I open this PR to optimize the computation of the KL divergence between two `MatrixNormalLinearOperator`s. As in #1497, the computation is valid and gives a visible speed up.
=> Optimize matrix_normal_linear_operator KL divergence computation.

setup.py
Resolves #1723
* Add requires-python metadata through the addition of setuptools's python_requires in setup.py.
- c.f. https://peps.python.org/pep-0621/#requires-python
* The addition of requires-python is to provide guards to keep older CPython versions from installing releases that could contain unrunnable code.
=> Add requires-python metadata

tensorflow_probability/python/math/linalg.py
This PR adds a boolean argument `return_pivoting_order` to `pivoted_cholesky`, which indicates whether or not the pivoting order `perm` used in the decomposition is returned along with the low rank Cholesky factor `lr`. The default value is `False` (in which case only `lr` is returned) to prevent breakages 🌷 
Corresponding issue: https://github.com/tensorflow/probability/issues/1734 ✨
=> Return pivoting order from `pivoted_cholesky`

tensorflow_probability/python/distributions/linear_gaussian_ssm.py
The equation in updating the posterior variance is called "Joseph form" instead of "Jordan form". Jordan form has nothing to do with this equation, reading the comment causes quite a bit of confusion.
=> Correct a misleading comment in linear_gaussian_ssm.py

tensorflow_probability/python/bijectors/cumsum.py
=> Quick fix.

tensorflow_probability/python/__init__.py
* In addition to recommending users install TensorFlow dependencies piecemeal, also recommend using the 'tf' extra to install all required dependencies to use tensorflow-probability with tensorflow.
* Split this off from the rest of the error message as it is already too long.
As this amends https://github.com/tensorflow/probability/commit/988f02323f16419086d761cc6cdd50b94aa03257 tagging @jburnim for review.
=> Recommend 'tensorflow-probability[tf]' extra on tf-keras import failure

tensorflow_probability/python/internal/structural_tuple.py
This PR introduces a new check for field names in a StructTuple, preventing any that over-ride existing members of the tuple base class.  It is intended to trap a gotcha in JointDistributionCoroutine if a user names a variable "index" or "count".
=> Field name checks for StructTuple

spinoffs/inference_gym/inference_gym/targets/dirichlet.py, spinoffs/inference_gym/inference_gym/targets/dirichlet_test.py
=> Add dirichlet distribution
