tensorflow/probability

- tensorflow_probability/examples/cifar10_bnn.py
- tensorflow_probability/examples/models/BResNet.py
- tensorflow_probability/examples/models/BVGG.py
- tensorflow_probability/examples/models/bayesian_resnet.py
- tensorflow_probability/examples/models/bayesian_vgg.py
This is an example for CIFAR-10 with ResNet18 and VGG16. With the current setup, the ResNet18 hits about 80% validation accuracy and 90% training accuracy.
The visualization for MNIST has been removed because the plots did not really look as I expected. The validation accuracy would be pretty high but the distributions plotted are still like a random dist. I'm unsure as to why that is happening so I removed it for now. If you would like it for debugging, I can include it. 
Please let me know if there are style changes needed.
> Example for CIFAR-10 with ResNet18 and VGG16

- tensorflow_probability/python/bijectors/real_nvp.py
- tensorflow_probability/python/bijectors/real_nvp_test.py
Extends RealNVP bijector to subclass from `ConditionalBijector` to allow conditioning.
#106
> Conditional real nvp

- tensorflow_probability/python/positive_semidefinite_kernels/rational_quadratic.py
fix import bug in python/positive_semidefinite_kernels/rational_quadratic.py
> fix rational_quadratic.py

- tensorflow_probability/python/bijectors/bijector.py
Hopefully this will save hours of debugging for the next guy :)
> fix bijector type mismatch error message

- tensorflow_probability/python/positive_semidefinite_kernels/BUILD
- tensorflow_probability/python/positive_semidefinite_kernels/__init__.py
- tensorflow_probability/python/positive_semidefinite_kernels/polynomial.py
- tensorflow_probability/python/positive_semidefinite_kernels/polynomial_test.py
Adding of the linear kernel (also known as dot-product kernel) for Gaussian Processes.
The kernel is based upon [chapter 4](http://www.gaussianprocess.org/gpml/chapters/RW4.pdf) from Gaussian Processes for Machine Learning by Carl Edward Rasmussen and Christopher K. I. Williams.
Proposal to add kernel was added in issue #193
> Linear positive semidefinite kernel

- tensorflow_probability/python/bijectors/bijector.py
- tensorflow_probability/python/bijectors/conditional_bijector_test.py
I have similar [PR open on the tensorflow side](https://github.com/tensorflow/tensorflow/pull/21534), but haven't received any response to it for months. I thought that now that the bijector lives in probability, maybe it would be best to move this here.
Right now, Bijector _Mapping's _deep_tuple doesn't allow nested dicts. This problem causes some of the conditioning to not work. See: https://github.com/tensorflow/tensorflow/issues/21543. This PR is a possible way to fix the issue. I'm happy to take feedback on this, and potentially fix the problem in some other way if needed.
> Bijector mapping  deep tuple fix

- .gitignore
- tensorflow_probability/python/distributions/BUILD
- tensorflow_probability/python/distributions/__init__.py
- tensorflow_probability/python/distributions/empirical.py
- tensorflow_probability/python/distributions/empirical_test.py
This PR tries to address issue #183 by implementing an Empirical distribution in TFP. It is adapted from Edward implementation (https://github.com/bleilab/edward/blob/master/edward/models/empirical.py) with some new methods and tests. Please let me know if there are any issues.
> Add Empirical distribution

- tensorflow_probability/python/mcmc/metropolis_hastings.py
Hi,
I think the log acceptance probability should look like this? Thanks!
> correct log_acceptance_probability

- tensorflow_probability/g3doc/api_docs/python/tfp/mcmc/sample_annealed_importance_chain.md
- tensorflow_probability/python/mcmc/sample_annealed_importance.py
Fix bug related to issue #376. Simple spelling mistake.
> Update sample_annealed_importance_chain.md (issue #376)

- tensorflow_probability/python/layers/dense_variational.py
this example is probably missing a "Local" :-)
> add missing Local

- tensorflow_probability/python/version.py
This had been done at pip pkg build time, but left pending.
> Update version suffix

- tensorflow_probability/python/bijectors/real_nvp.py
- tensorflow_probability/python/bijectors/real_nvp_test.py
As mentioned in #662, it would be nice if the number of masked elements in RealNVP could be defined as proportions instead of just integers.
Happy to take feedback on this.
> Real nvp floating num masked

- tensorflow_probability/python/distributions/distribution.py
Assert the prob/value in the quantile method in distribution base class when validate_args is true
Resolve #714
> add assert p in [0, 1] in quantile method in distribution base class

- tensorflow_probability/python/distributions/laplace.py
Should solve #712 by giving the Laplace distribution a quantile method.
> Add quantile method to distirbutions.Laplace

- tensorflow_probability/python/util/deferred_tensor.py
- tensorflow_probability/python/util/deferred_tensor_test.py
Adds `DeferredTensor.numpy`. See #731.
> Add DeferredTensor.numpy

- tensorflow_probability/g3doc/api_docs/python/tfp/stats/percentile.md
- tensorflow_probability/g3doc/api_docs/python/tfp/stats/quantiles.md
- tensorflow_probability/python/stats/quantiles.py
- tensorflow_probability/python/stats/quantiles_test.py
> replace 'keep_dims' with 'keepdims' in quantiles.py

- tensorflow_probability/python/bijectors/masked_autoregressive.py
Example in documentation previously didn't run
> Fixed an example

- tensorflow_probability/python/bijectors/bijector.py
Fixed some typos in bijector class documentation
> Fixed some typos

- tensorflow_probability/examples/jupyter_notebooks/Linear_Mixed_Effects_Models.ipynb
> Fix typo in np.ndarray

- tensorflow_probability/python/sts/smooth_seasonal.py
Fix typos by adding the missing 1
> Fix typos in documentation for smoothing

- tensorflow_probability/python/distributions/variational_gaussian_process.py
See #739 for previous discussion.
The `VariationalGaussianProcess` was reformulated using a `VariationalKernel` similar to the `SchurComplement`-Kernel. This kernel is defined with respect to the inducing points `Z` and contains a cholesky decomposition of the `kernel.matrix(Z, Z)` matrix. It is computed here:
https://github.com/tensorflow/probability/blob/e0346910ecca45f6ee83a7deccb3fe7d690e296a/tensorflow_probability/python/distributions/variational_gaussian_process.py#L127
Let's take a look at this relatively simple example using `tfp.layers` for interop with keras. This is meant as a relatively real-worldy example, I'm aware it is not quite minimal.
```python
import numpy as np
import tensorflow as tf
class RBFLayer(tf.keras.layers.Layer):
def …
```
> Add diagonal shift in VariationalKernel

- tensorflow_probability/python/bijectors/BUILD
- tensorflow_probability/python/bijectors/__init__.py
- tensorflow_probability/python/bijectors/bijector_properties_test.py
- tensorflow_probability/python/bijectors/bijector_test_util.py
- tensorflow_probability/python/bijectors/frechet_cdf.py
- tensorflow_probability/python/bijectors/frechet_cdf_test.py
- tensorflow_probability/python/bijectors/hypothesis_testlib.py
Implement the Fréchet cdf (https://en.wikipedia.org/wiki/Fréchet_distribution).
> Add the Frechet cdf

- tensorflow_probability/python/distributions/cauchy.py
- tensorflow_probability/python/distributions/cauchy_test.py
KL calculation is based on [this paper](https://arxiv.org/pdf/1905.10965.pdf).
> Added KL divergence calculation between two Cauchy distributions.

- tensorflow_probability/python/math/interpolation.py
Corrected a error in example code in the documentation.
> Correction of a Documentation Error

- tensorflow_probability/python/optimizer/lbfgs.py
- tensorflow_probability/python/optimizer/lbfgs_test.py
This is a very small change that adds support for resuming lbfgs minimization if previously stopped by the stopping condition. If this design isn't the preferred one, happy to change the PR---I could also change the name of the argument to `experimental_initial_state` if you think it's not necessarily the way the API should look.
This means you can run the optimizer with `converged_any` and every time a single model converges from the batch, you can swap out the converged model and continue optimizing. For our problem, this gives us a 15-40% speed-up; we use batch optimisation for different hyperparameter settings, and strongly regularised models converge much quicker. Being able to stop evaluating them for the remaining iterations is an important optimisation.
Fixes #924 
Here's some …
> lbfgs: support passing in `previous_optimizer_results`

- tensorflow_probability/python/distributions/BUILD
- tensorflow_probability/python/distributions/__init__.py
- tensorflow_probability/python/distributions/distribution_properties_test.py
- tensorflow_probability/python/distributions/loglogistic.py
- tensorflow_probability/python/distributions/loglogistic_test.py
Formula from the
Handbook of Differential Entropy, J.V. Michalowicsz, J.M. Nichols, F. Bucholtz
p. 113, 114
> Implement loglogistic distribution

- tensorflow_probability/python/version.py
PR also Includes cherrypick of past change to support later cloudpickle versions
> Increment patch number 0 -> 1

- tensorflow_probability/python/bijectors/BUILD
- tensorflow_probability/python/bijectors/__init__.py
- tensorflow_probability/python/bijectors/ascending.py
- tensorflow_probability/python/bijectors/ascending_test.py
- tensorflow_probability/python/bijectors/bijector_properties_test.py
- tensorflow_probability/python/bijectors/hypothesis_testlib.py
- tensorflow_probability/python/bijectors/ordered.py
- tensorflow_probability/python/distributions/hypothesis_testlib.py
- tensorflow_probability/python/distributions/ordered_logistic_test.py
- tensorflow_probability/python/experimental/vi/parameter_constraints.py
> Introduce Ascending bijector equivalent to Invert(Ordered())

- tensorflow_probability/python/mcmc/replica_exchange_mc.py
Fixes several issues with the examples in the `ReplicaExchangeMC`
docstring:
- first example:
- the `dtype = tf.float32` line led to errors later when trying to
instantiate a variable with such a type, because `tf.float32` is not
callable
- the trace function passed to `sample_chain` returns a tuple, which
was not properly taken into account when storing the result of the
`sample_chain` call, which led to an exception after finishing sampling
- the `seed` argument of `make_kernel_fn` is deprecated, which
resulted in a warning for each and every HMC sample
- although only a minor nitpick, but the chosen HMC step sizes were
somewhat too small and resulted in HMC acceptance rates of ~0.99,
which gives a bad example
- second example:
- same issue as above with `dtype = tf.float32`
- when …
> Fix examples in Replica Exchange docstring

- tensorflow_probability/python/bijectors/rational_quadratic_spline.py
- tensorflow_probability/python/bijectors/rational_quadratic_spline_test.py
> Update RationalQuadraticSpline example to use inputs with non-unit batch size

- tensorflow_probability/python/math/psd_kernels/feature_transformed_test.py
The file docstring was most likely a copy paste from a Bijector submodule file.
> Change file docstring

- tensorflow_probability/python/bijectors/bijector.py
Fixes a minor typo in an error message
> Fixed typo in error message

- tensorflow_probability/examples/jupyter_notebooks/Gaussian_Process_Regression_In_TFP.ipynb
matplotlib.pyplot wasn't imported so i added 
`"import matplotlib.pyplot as plt\n",`
> Imported missing matplotlib.pyplot

- tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_VAE.ipynb
`tf.data.AUTOTUNE` <- `tf.data.experimental.AUTOTUNE`  cc @lamberta @MarkDaoust 
Hope this helps
> `tf.data.AUTOTUNE` <- `tf.data.experimental.AUTOTUNE`

- tensorflow_probability/python/sts/components/autoregressive_moving_average.py
- tensorflow_probability/python/sts/components/autoregressive_moving_average_test.py
@davmre clean PR with correct cla! `log_prob` issue is resolved, just needed to kick off the recursion in a similar manner as `autoregressive_test.py`. Lmk if there is anything else we need before we merge, enjoy the long weekend!
> Autoregressive moving average cla

- tensorflow_probability/python/experimental/nn/util/kernel_bias.py
Updated "Recomendations" to "Recommendations"
> Fixed typo in kernel_bias.py

- CONTRIBUTING.md
- discussion/technical_note_on_unrolled_nuts.md
- discussion/turnkey_inference_candidate/README.md
- discussion/turnkey_inference_candidate/window_tune_nuts_sampling.py
- spinoffs/inference_gym/README.md
- spinoffs/inference_gym/model_contract.md
- tensorflow_probability/examples/jupyter_notebooks/Undocumented_Infection_and_the_Dissemination_of_SARS-CoV2.ipynb
- tensorflow_probability/python/experimental/distributions/marginal_fns.py
- tensorflow_probability/python/experimental/mcmc/preconditioned_nuts.py
- tensorflow_probability/python/mcmc/internal/slice_sampler_utils.py
- tensorflow_probability/python/mcmc/nuts.py
Signed-off-by: Ryan Russell <git@ryanrussell.org>
> Improve Readability

- tensorflow_probability/python/mcmc/diagnostic.py
There was a reference to R-hat paper arxiv version, and I just updated it with the journal publication info.
> Update the R-hat paper reference

- .github/workflows/continuous-integration.yml
- testing/pylintrc
This should make the PR checks less noisy and more useful.
> Update python testing version and pylintrc

- tensorflow_probability/python/experimental/nn/util/kernel_bias.py
Refer : https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/python/ops/init_ops.py#L474-L478
> Constant value is from standard deviation not Variance
